# if empty, disable TiDB SQL tests
host = "10.2.1.2"
port = 54000
user = "root"
password = ""

# if empty, disable MVCC tests
pd = ""


[scheduler]
# pd = ["http://127.0.0.1:2379"]
# shuffle-leader = false
# shuffle-region = false

[suite]
names = ["bank", "bank2", "ledger", "crud", "block_writer","log"]
concurrency = 10000

[suite.bank]
num_accounts = 100000000
interval = "2s"
table_num = 1

[suite.bank2]
num_accounts = 100000000
interval = "2s"
contention = "low"

[suite.ledger]
num_accounts = 10
interval = "2s"

[suite.crud]
user_count = 1000
post_count = 10000
update_users = 20
update_posts = 200
interval = "2s"

[suite.log]
max_count = 100000000
delete_count = 100000
interval = "2s"
table_num = 1

[suite.block_writer]
table_num = 1

[mvcc]
names = ["bank"]
concurrency = 10

[mvcc.bank]
num_accounts = 10000
interval = "1s"

[serial_suite]
names = ["sysbench", "sqllogic_test"]

[serial_suite.sysbench] 
table_count = 8
table_size = 1000000
threads = 8 
max_time = 1800 
interval = "1h"
database = "sbtest"
lua_path = "./sysbench_lua"


[serial_suite.sqllogic_test] 
test_path = "./sqllogic_test"
parallel = 8
skipError = false
database = "test"

[metric]
job = "stability_test"
address = ""
interval = "5s"


