# if empty, disable TiDB SQL tests
host = "10.2.1.2"
port = 54000
user = "root"
password = ""

# if empty, disable MVCC tests
pd = ""

[nemeses]
wait = "1m"
ranges = ["one"]

[nemeses.targets]
pd = ["pd-2"]
tikv = ["tikv-3", "tikv-4", "tikv-5", "tikv-6", "tikv-7"]
tidb = ["tidb-2"]

[nemeses.cfgs]
kill = """
wait = "30s"
"""
lantency = """
wait = "1m"
dev = "eth0"
lantency = 30
range = 5
"""

[suite]
names = ["bank", "bank2", "ledger", "crud", "block_writer", "log", "ddl"]
concurrency = 10000

[suite.bank]
num_accounts = 100000000
interval = "2s"
table_num = 1

[suite.bank2]
num_accounts = 100000000
interval = "2s"
contention = "low"

[suite.ledger]
num_accounts = 10
interval = "2s"

[suite.crud]
user_count = 1000
post_count = 10000
update_users = 20
update_posts = 200
interval = "2s"

[suite.log]
max_count = 100000000
delete_count = 100000
interval = "2s"
table_num = 1

[suite.block_writer]
table_num = 1

[suite.ddl]
tables_to_create = 100

[mvcc]
names = ["bank"]
concurrency = 10

[mvcc.bank]
num_accounts = 10000
interval = "1s"

[metric]
job = "stability_test"
address = ""
interval = "5s"

[cluster.ssh]
user = "pingcap"
port = 22

[[cluster.services]]
name = "pd-2"
host = "10.2.1.2"
type = "docker"

[[cluster.services]]
name = "tikv-3"
host = "10.2.1.3"
type = "docker"

[[cluster.services]]
name = "tikv-4"
host = "10.2.1.4"
type = "docker"

[[cluster.services]]
name = "tikv-5"
host = "10.2.1.5"
type = "docker"

[[cluster.services]]
name = "tikv-6"
host = "10.2.1.6"
type = "docker"

[[cluster.services]]
name = "tikv-7"
host = "10.2.1.7"
type = "docker"

[[cluster.services]]
name = "tidb1"
host = "10.2.1.2"
type = "docker"
