# if empty, disable TiDB SQL tests
host = "10.2.1.2"
port = 54000
user = "root"
password = ""

# if empty, disable MVCC tests
pd = ""

[scheduler]
pd = ["http://127.0.0.1:2379"]
shuffle-leader = false
shuffle-region = false

[suite]
names = ["bank", "bank2", "ledger", "crud", "block_writer","log", "mvcc_bank", "sysbench", "sqllogic_test"]

[suite.bank]
num_accounts = 10000000
interval = "2s"
table_num = 1
concurrency = 1000 

[suite.bank2]
num_accounts = 1000000
interval = "2s"
contention = "low"
concurrency = 1000 

[suite.ledger]
num_accounts = 10
interval = "2s"
concurrency = 1000 

[suite.crud]
user_count = 1000
post_count = 1000
update_users = 20
update_posts = 200
interval = "2s"
concurrency = 1000 

[suite.log]
max_count = 100000000
delete_count = 100000
interval = "2s"
table_num = 1
concurrency = 1000 

[suite.block_writer]
table_num = 1
concurrency = 1000 

[suite.mvcc_bank]
num_accounts = 10000
interval = "1s"
concurrency = 8

[suite.sysbench]
table_count = 8
table_size = 1000000
threads = 8
max_time = 1800
interval = "1h"
database = "sbtest"
lua_path = "./sysbench_lua"


[suite.sqllogic_test]
test_path = "./sqllogictest"
parallel = 8
skipError = true
database = "test"

[metric]
job = "stability_test"
address = ""
interval = "5s"


