port = 20170
dir = "."
log_dir = "logs"

[ansible]
dir = "ansible"

[[ansible.clusters]]
name = "benchbot"
host = "127.0.0.1"
port = 4000
db = "test"
user = "root"
password = ""

[suites.block-write]
duration = "1m"
warm_up = "5m"
num_threads = 100
min_block_size = 3000
max_block_size = 4000

[suites.sysbench]
warm_up = "5m"
scripts_dir = "sysbench"

[suites.tpch]
host = "127.0.0.1"
port = 4000
scripts_dir = "tpch_scripts"

[suites.ycsb]
duration = "1m"
warm_up = "5m"
num_threads = 100
workloads = ["a", "b"]
databases = [
    "raw://127.0.0.1:2379",
    "txn://127.0.0.1:2379",
    "tidb://root@tcp(127.0.0.1:4000)/",
]
