port = 20170
dir = "."
log_dir = "logs"

[ansible]
dir = "ansible"

[[ansible.clusters]]
name = "benchbot"
host = "127.0.0.1"
port = 4000
db = "test"
user = "root"
password = ""

[suites.block-write]
num_threads = 100
num_requests = 100000
min_block_size = 3000
max_block_size = 4000

[suites.sysbench-oltp]
table_size = 100000
num_tables = 10
num_threads = 100
num_requests = 100000

[suites.sysbench-simple]
num_tables = 10
num_threads = 100
num_selects = 100000
num_inserts = 100000
num_deletes = 100000

[suites.tpch]
host = "127.0.0.1"
port = 4000
scripts_dir = "tpch_scripts"

[suites.ycsb]
databases = [
    "raw://127.0.0.1:2379",
    "txn://127.0.0.1:2379",
    "tidb://root@tcp(127.0.0.1:4000)/",
]
workloads = ["a", "b"]
num_threads = 100
num_initials = 100000
num_requests = 100000
