port = 20170
dir = "."

[ansible]
dir = "ansible"

[[ansible.clusters]]
name = "benchbot"
host = "127.0.0.1"
port = 4000
db = "test"
user = "root"
password = ""

[suites.simple-ops]
num_tables = 10
num_threads = 100
num_requests = 1000000

[suites.simple-oltp]
table_size = 1000000
num_tables = 10
num_threads = 100
num_requests = 1000000

[suites.block-write]
num_threads = 100
num_requests = 100000
min_block_size = 1000
max_block_size = 2000