
dir = "./"
port = 20170

[ansible]
dir = "./ansible"

[[ansible.clusters]]
name = "local-3306"
host = "127.0.0.1"
port = 3306
db = "test"
user = "root"
password = ""

[[ansible.clusters]]
name = "local-3307"
host = "127.0.0.1"
port = 3307
db = "test"
user = "root"
password = ""

[bench]
cases = [
	"block_write",
]
